name: Quality Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar JDK 11 usando Adoptium
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # Usamos Adoptium (temurin es el nombre oficial para JDK de Adoptium)

      # Paso 3: Cache de dependencias de Gradle (opcional)
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Paso 4: Configurar Android SDK
      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          target: google_apis
          force-avd-creation: true

      # Paso 5: Construir el proyecto Android con Gradle
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # Paso 6: Ejecutar pruebas unitarias
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --no-daemon
